const DIAGNOSTICO1_ITEMS = [
  [1, "¿Evalúa la rentabilidad esperada del cultivo antes de iniciar cada ciclo?", "1. Inicio", "Financiera", false],
  [2, "¿Define metas de producción antes de iniciar cada ciclo?", "1. Inicio", "Formulación y Gerencia de Proyectos", false],
  [3, "¿Establece metas de ingresos o ganancias esperadas por ciclo?", "1. Inicio", "Financiera", false],
  [4, "¿Evalúa si cuenta con suficiente capital para iniciar el cultivo?", "1. Inicio", "Financiera", false],
  [5, "¿Consulta precios del mercado antes de sembrar?", "1. Inicio", "Comercialización y Mercadeo", false],
  [6, "¿Define quiénes participarán en las labores del cultivo?", "1. Inicio", "Formulación y Gerencia de Proyectos", false],
  [7, "¿Tiene claro a quién venderá la cosecha antes de sembrar?", "1. Inicio", "Comercialización y Mercadeo", false],
  [8, "¿Identifica los principales problemas productivos antes de comenzar?", "1. Inicio", "Gestión de Riesgos", false],
  [9, "¿Trabaja coordinadamente con otros productores o asociaciones?", "1. Inicio", "Asociatividad y Liderazgo", false],
  [10, "¿Reconoce fortalezas y debilidades de su unidad productiva?", "1. Inicio", "Formulación y Gerencia de Proyectos", false],
  [11, "¿Elabora un presupuesto total antes de iniciar la siembra?", "2. Planificación", "Financiera", false],
  [12, "¿Calcula los costos de mano de obra y jornales?", "2. Planificación", "Financiera", false],
  [13, "¿Calcula los costos de insumos, fertilizantes y transporte?", "2. Planificación", "Financiera", false],
  [14, "¿Organiza las actividades del cultivo en un cronograma de trabajo?", "2. Planificación", "Formulación y Gerencia de Proyectos", false],
  [15, "¿Define las fechas de preparación, siembra y cosecha con anticipación?", "2. Planificación", "Formulación y Gerencia de Proyectos", false],
  [16, "¿Planifica cuántas personas necesita en cada etapa del cultivo?", "2. Planificación", "Formulación y Gerencia de Proyectos", false],
  [17, "¿Define metas de productividad por hectárea antes de sembrar?", "2. Planificación", "Formulación y Gerencia de Proyectos", false],
  [18, "¿Gestiona crédito o financiamiento formal para su cultivo?", "2. Planificación", "Financiera", false],
  [19, "¿Adquiere insumos con anticipación para evitar sobrecostos?", "2. Planificación", "Financiera", false],
  [20, "¿Evalúa riesgos climáticos antes de iniciar la siembra?", "2. Planificación", "Gestión de Riesgos", false],
  [21, "¿Evalúa riesgos fitosanitarios (plagas y enfermedades) antes de sembrar?", "2. Planificación", "Gestión de Riesgos", false],
  [22, "¿Cuenta con un plan alternativo si la cosecha falla o los precios bajan?", "2. Planificación", "Gestión de Riesgos", false],
  [23, "¿Planifica el uso eficiente del agua durante el ciclo productivo?", "2. Planificación", "Sostenibilidad y Entorno", false],
  [24, "¿Planifica el uso de maquinaria o herramientas por etapa del cultivo?", "2. Planificación", "Tecnología e Innovación", false],
  [25, "(*) ¿Siembra sin consultar previamente los precios del mercado?", "2. Planificación", "Comercialización y Mercadeo", true],
  [26, "¿Cumple el cronograma de actividades planificado durante el cultivo?", "3. Ejecución", "Formulación y Gerencia de Proyectos", false],
  [27, "¿Registra los gastos y pagos realizados durante el cultivo?", "3. Ejecución", "Financiera", false],
  [28, "¿Usa una herramienta (cuaderno, app o Excel) para llevar sus cuentas?", "3. Ejecución", "Financiera", false],
  [29, "¿Supervisa el desempeño de los trabajadores o jornaleros?", "3. Ejecución", "Asociatividad y Liderazgo", false],
  [30, "¿Consulta información técnica o de precios usando su celular u otros medios?", "3. Ejecución", "Tecnología e Innovación", false],
  [31, "¿Mantiene comunicación activa con compradores potenciales durante el cultivo?", "3. Ejecución", "Comercialización y Mercadeo", false],
  [32, "¿Busca asistencia técnica cuando surge un problema productivo?", "3. Ejecución", "Tecnología e Innovación", false],
  [33, "¿Ajusta sus actividades cuando cambian las condiciones del entorno?", "3. Ejecución", "Gestión de Riesgos", false],
  [34, "¿Reduce desperdicios de insumos y materiales durante la ejecución?", "3. Ejecución", "Sostenibilidad y Entorno", false],
  [35, "¿Verifica la calidad de los insumos antes de aplicarlos al cultivo?", "3. Ejecución", "Tecnología e Innovación", false],
  [36, "(*) ¿Realiza gastos sin llevar ningún tipo de registro?", "3. Ejecución", "Financiera", true],
  [37, "¿Lleva un control periódico del avance del cultivo?", "4. Monitoreo y Control", "Formulación y Gerencia de Proyectos", false],
  [38, "¿Compara regularmente lo ejecutado con lo planificado?", "4. Monitoreo y Control", "Formulación y Gerencia de Proyectos", false],
  [39, "¿Mide los costos reales acumulados durante el ciclo?", "4. Monitoreo y Control", "Financiera", false],
  [40, "¿Detecta desviaciones del presupuesto a tiempo para corregirlas?", "4. Monitoreo y Control", "Financiera", false],
  [41, "¿Mide el rendimiento del cultivo por hectárea?", "4. Monitoreo y Control", "Tecnología e Innovación", false],
  [42, "¿Controla las pérdidas ocasionadas por plagas o condiciones climáticas?", "4. Monitoreo y Control", "Gestión de Riesgos", false],
  [43, "¿Corrige los problemas del cultivo de forma oportuna cuando aparecen?", "4. Monitoreo y Control", "Gestión de Riesgos", false],
  [44, "¿Monitorea la calidad del producto durante su desarrollo?", "4. Monitoreo y Control", "Comercialización y Mercadeo", false],
  [45, "¿Controla el flujo de caja durante el ciclo productivo?", "4. Monitoreo y Control", "Financiera", false],
  [46, "¿Compara los resultados actuales con los de ciclos anteriores?", "4. Monitoreo y Control", "Formulación y Gerencia de Proyectos", false],
  [47, "¿Toma decisiones basadas en indicadores o registros del cultivo?", "4. Monitoreo y Control", "Tecnología e Innovación", false],
  [48, "¿Documenta las incidencias o problemas ocurridos durante el cultivo?", "4. Monitoreo y Control", "Formulación y Gerencia de Proyectos", false],
  [49, "(*) ¿Toma decisiones sobre el cultivo sin revisar los resultados anteriores?", "4. Monitoreo y Control", "Formulación y Gerencia de Proyectos", true],
  [50, "¿Planifica la cosecha con suficiente anticipación?", "5. Cierre", "Formulación y Gerencia de Proyectos", false],
  [51, "¿Coordina el transporte de la cosecha con anticipación para evitar pérdidas?", "5. Cierre", "Comercialización y Mercadeo", false],
  [52, "¿Negocia precios con diferentes compradores antes de vender?", "5. Cierre", "Comercialización y Mercadeo", false],
  [53, "¿Busca alternativas de venta directa sin intermediarios?", "5. Cierre", "Comercialización y Mercadeo", false],
  [54, "¿Calcula la utilidad o pérdida total al finalizar el ciclo?", "5. Cierre", "Financiera", false],
  [55, "¿Ahorra parte de las ganancias para financiar el siguiente ciclo?", "5. Cierre", "Financiera", false],
  [56, "¿Evalúa el cumplimiento de las metas establecidas al inicio?", "5. Cierre", "Formulación y Gerencia de Proyectos", false],
  [57, "¿Analiza los errores cometidos durante el proceso para no repetirlos?", "5. Cierre", "Formulación y Gerencia de Proyectos", false],
  [58, "¿Conserva registros del ciclo para apoyar decisiones futuras?", "5. Cierre", "Tecnología e Innovación", false],
  [59, "¿Comparte los aprendizajes del ciclo con otros productores o asociados?", "5. Cierre", "Asociatividad y Liderazgo", false],
  [60, "(*) ¿Termina el ciclo sin evaluar si cumplió sus metas iniciales?", "5. Cierre", "Formulación y Gerencia de Proyectos", true],
  [61, "¿Aplica prácticas agrícolas amigables con el medio ambiente?", "6. Valor Agregado", "Sostenibilidad y Entorno", false],
  [62, "¿Reutiliza residuos agrícolas (hojas, tallos, etc.) en el proceso productivo?", "6. Valor Agregado", "Sostenibilidad y Entorno", false],
  [63, "¿Ha probado nuevas variedades de yuca para mejorar el rendimiento?", "6. Valor Agregado", "Tecnología e Innovación", false],
  [64, "¿Participa en capacitaciones o talleres técnicos del sector?", "6. Valor Agregado", "Tecnología e Innovación", false],
  [65, "¿Experimenta con nuevas prácticas o métodos para mejorar su cultivo?", "6. Valor Agregado", "Tecnología e Innovación", false]
].map(([numero, pregunta, seccion, dimension, inversa]) => ({
  numero,
  pregunta,
  seccion,
  dimension,
  inversa
}));

module.exports = {
  DIAGNOSTICO1_ITEMS
};
