# Exported from Render on 2026-06-13T02:40:38Z
version: "1"
services:
- type: web
  name: server-yuca-4
  runtime: node
  repo: https://github.com/prkaido/Yuca
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: NGROK_ENABLED
    sync: false
  - key: NODE_VERSION
    sync: false
  region: virgina
  buildCommand: npm ci
  startCommand: npm start
  healthCheckPath: /api/health
  autoDeployTrigger: commit
